options:
    formatter: stylish
files:
    include: 'src/scss/**/*.scss'
    ignore:
        - 'src/scss/vendor/**/*.scss'
rules:
    class-name-format: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    no-color-literals: 0
    no-qualifying-elements: 0
    indentation:
        - 1
        -
            size: 4
